name: Modern_Physics_project
channels:
  - conda-forge
dependencies:
  - numpy<2.0.0
  - matplotlib
  - scipy
  - pandas
  - pip
  - pip:
      - tikzplotlib
      - webcolors~1.11.1
  - pywavelets
  - typing_extensions


